"""added roles

Revision ID: 0e5c55149015
Revises: c5040004c572
Create Date: 2025-05-23 03:33:45.234259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5c55149015'
down_revision: Union[str, None] = 'c5040004c572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Создай Enum типы вручную
user_role_enum = sa.Enum('USER', 'ADMIN', 'MODERATOR', name='userrole')
subscription_type_enum = sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='subscriptiontype')
def upgrade() -> None:
    """Upgrade schema."""
        # Сначала создаём типы
    user_role_enum.create(op.get_bind(), checkfirst=True)
    subscription_type_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.Enum('USER', 'ADMIN', 'MODERATOR', name='userrole'), nullable=False, server_default='USER'))
    op.add_column('user', sa.Column('subscription_type', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='subscriptiontype'), nullable=False, server_default='FREE'))
    op.add_column('user', sa.Column('subscription_expire_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscription_expire_date')
    op.drop_column('user', 'subscription_type')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###

    subscription_type_enum.drop(op.get_bind(), checkfirst=True)
    user_role_enum.drop(op.get_bind(), checkfirst=True)
