"""added alert and telegram

Revision ID: 3294da63ae2d
Revises: 0e5c55149015
Create Date: 2025-06-06 01:24:44.712121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3294da63ae2d'
down_revision: Union[str, None] = '0e5c55149015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_item',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_symbol', sa.String(), nullable=False),
    sa.Column('less_than', sa.Float(), nullable=True),
    sa.Column('more_than', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.CheckConstraint('(less_than IS NULL AND more_than IS NOT NULL) OR (less_than IS NOT NULL AND more_than IS NULL)', name='only_one_threshold_check'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_item_id'), 'alert_item', ['id'], unique=False)
    op.add_column('user', sa.Column('telegram_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'telegram_id')
    op.drop_index(op.f('ix_alert_item_id'), table_name='alert_item')
    op.drop_table('alert_item')
    # ### end Alembic commands ###
