"""fixed telegram

Revision ID: 707352778c00
Revises: 3294da63ae2d
Create Date: 2025-06-06 02:43:04.360389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '707352778c00'
down_revision: Union[str, None] = '3294da63ae2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "user" ALTER COLUMN telegram_id TYPE BIGINT USING telegram_id::bigint')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'telegram_id',
               existing_type=sa.BIGINT(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
