"""added error column

Revision ID: 57317bb29dd9
Revises: 9d719b4e4df0
Create Date: 2025-06-10 00:40:15.243844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57317bb29dd9'
down_revision: Union[str, None] = '9d719b4e4df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_logs', sa.Column('error', sa.String(), nullable=True))
    op.add_column('email_logs', sa.Column('traceback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_logs', 'traceback')
    op.drop_column('email_logs', 'error')
    # ### end Alembic commands ###
