"""added ticker string

Revision ID: 6f7eea2d3ff3
Revises: 60d20f3bce87
Create Date: 2025-05-21 21:07:39.970639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7eea2d3ff3'
down_revision: Union[str, None] = '60d20f3bce87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stockprice', sa.Column('ticker', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stockprice', 'ticker')
    # ### end Alembic commands ###
